import type { Product, Branch, Category, Testimonial, GalleryItem } from '@/types'

export const categories: Category[] = [
  { id: 'living', name: 'Living Room', count: 142, icon: '🛋️', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80', span: true },
  { id: 'bedroom', name: 'Bedroom', count: 98, icon: '🛏️', image: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&q=80' },
  { id: 'dining', name: 'Dining Room', count: 76, icon: '🍽️', image: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=800&q=80' },
  { id: 'office', name: 'Office', count: 64, icon: '💼', image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80' },
  { id: 'hotel', name: 'Hotel', count: 53, icon: '🏨', image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80' },
  { id: 'outdoor', name: 'Outdoor', count: 41, icon: '🌿', image: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800&q=80' },
]

export const products: Product[] = [
  {
    id: '1',
    name: 'Royal Velvet Sofa Set',
    description: '3-piece luxury sofa in premium Ethiopian leather',
    price: 28500,
    category: 'living',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800&q=80',
    tag: 'bestseller',
    rating: 5,
    reviewCount: 48,
    materials: ['Premium leather', 'Solid mahogany frame', 'High-density foam'],
    dimensions: 'L: 220cm × W: 90cm × H: 85cm',
    colors: ['Camel Brown', 'Jet Black', 'Ivory White'],
  },
  {
    id: '2',
    name: 'Heritage King Bed',
    description: 'Solid mahogany frame with hand-carved headboard',
    price: 42000,
    category: 'bedroom',
    image: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=800&q=80',
    tag: 'new',
    rating: 5,
    reviewCount: 31,
    materials: ['Solid mahogany', 'Hand-carved details', 'Anti-scratch finish'],
    dimensions: 'L: 220cm × W: 200cm × H: 140cm',
    colors: ['Dark Walnut', 'Natural Mahogany', 'Ebony'],
  },
  {
    id: '3',
    name: 'Addis Dining Table',
    description: '8-seat solid wood dining set with cushioned chairs',
    price: 35800,
    category: 'dining',
    image: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=800&q=80',
    tag: 'custom',
    rating: 4,
    reviewCount: 22,
    materials: ['Solid teak wood', 'Fabric upholstery', 'Steel legs'],
    dimensions: 'Table: L: 240cm × W: 100cm',
    colors: ['Natural Teak', 'Wenge', 'Ash Grey'],
  },
  {
    id: '4',
    name: 'Executive Office Suite',
    description: 'Complete office setup: desk, chair, bookshelf',
    price: 19200,
    salePrice: 24000,
    category: 'office',
    image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=800&q=80',
    tag: 'sale',
    rating: 5,
    reviewCount: 57,
    materials: ['MDF with veneer', 'Ergonomic foam', 'Chrome hardware'],
    dimensions: 'Desk: L: 160cm × W: 80cm',
    colors: ['Dark Oak', 'Walnut', 'White'],
  },
  {
    id: '5',
    name: 'Boutique Hotel Armchair',
    description: 'Luxury accent chair for hotel lobbies and suites',
    price: 8900,
    category: 'hotel',
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
    tag: 'new',
    rating: 5,
    reviewCount: 19,
    materials: ['Velvet upholstery', 'Solid wood frame', 'Brass feet'],
    dimensions: 'W: 80cm × D: 82cm × H: 90cm',
    colors: ['Emerald Green', 'Navy Blue', 'Dusty Rose'],
  },
  {
    id: '6',
    name: 'Garden Teak Set',
    description: 'Weather-resistant outdoor dining set for 6',
    price: 22000,
    category: 'outdoor',
    image: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800&q=80',
    rating: 4,
    reviewCount: 14,
    materials: ['Grade A teak', 'Stainless steel', 'UV-resistant finish'],
    dimensions: 'Table: L: 200cm × W: 90cm',
    colors: ['Natural Teak', 'Weathered Grey'],
  },
  {
    id: '7',
    name: 'Melaku Wardrobe',
    description: '4-door sliding wardrobe with mirror panels',
    price: 31500,
    category: 'bedroom',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800&q=80',
    tag: 'bestseller',
    rating: 5,
    reviewCount: 63,
    materials: ['Melamine board', 'Mirror panels', 'Soft-close hinges'],
    dimensions: 'W: 240cm × D: 60cm × H: 220cm',
    colors: ['White', 'Graphite', 'Oak'],
  },
  {
    id: '8',
    name: 'Coffee Table Set',
    description: 'Nested marble-top coffee tables, set of 3',
    price: 12800,
    category: 'living',
    image: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=800&q=80',
    rating: 4,
    reviewCount: 28,
    materials: ['Italian marble top', 'Brass-coated steel frame'],
    dimensions: 'Main: W: 100cm × H: 42cm',
    colors: ['White Marble/Gold', 'Black Marble/Black'],
  },
]

export const branches: Branch[] = [
  {
    id: '1',
    city: 'Bishoftu',
    name: 'Bishoftu Main Office',
    address: 'Main Road, Near Lake Bishoftu, Bishoftu',
    phone: '+251 91 123 4567',
    hours: 'Mon–Sat: 8AM–8PM | Sun: 10AM–6PM',
    type: 'Headquarters + Showroom + Workshop',
    mapUrl: 'https://maps.google.com/?q=Bishoftu+Ethiopia',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80',
  },
  {
    id: '2',
    city: 'Addis Ababa',
    name: 'Addis Ababa Branch',
    address: 'Bole Road, Near Edna Mall, Addis Ababa',
    phone: '+251 91 234 5678',
    hours: 'Mon–Sat: 9AM–7PM',
    type: 'Showroom',
    mapUrl: 'https://maps.google.com/?q=Bole+Road+Addis+Ababa',
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80',
  },
]

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Amsale Mekonnen',
    role: 'Homeowner, Bole, Addis Ababa',
    quote: 'I furnished my entire villa with Melaku Furniture pieces. The quality is outstanding — guests always ask where I got my furniture. Worth every birr.',
    rating: 5,
    initials: 'AM',
  },
  {
    id: '2',
    name: 'Daniel Tesfaye',
    role: 'Hotel Owner, Bishoftu',
    quote: 'We furnished our boutique hotel with their hotel collection. The craftsmanship is unmatched and the custom work was delivered exactly on schedule.',
    rating: 5,
    initials: 'DT',
  },
  {
    id: '3',
    name: 'Sara Tadesse',
    role: 'Interior Designer, Addis Ababa',
    quote: 'The custom bedroom set they made is absolutely beautiful. They listened to every detail and the final result exceeded my expectations completely.',
    rating: 5,
    initials: 'ST',
  },
  {
    id: '4',
    name: 'Yonas Bekele',
    role: 'Business Owner, Bishoftu',
    quote: 'Their office furniture line transformed our workspace. Modern, durable, and our team loves it. Highly recommend the executive collection.',
    rating: 5,
    initials: 'YB',
  },
  {
    id: '5',
    name: 'Mekdes Alemu',
    role: 'Architect, Addis Ababa',
    quote: 'As an architect I recommend Melaku Furniture to all my clients. Their ability to customize to exact specifications is truly exceptional.',
    rating: 5,
    initials: 'MA',
  },
  {
    id: '6',
    name: 'Biruk Girma',
    role: 'Restaurant Owner, Bishoftu',
    quote: 'We equipped our entire restaurant with their outdoor and dining collection. Beautiful quality, and still looks perfect 2 years later.',
    rating: 4,
    initials: 'BG',
  },
]

export const galleryItems: GalleryItem[] = [
  { id: '1', image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600&q=80', alt: 'Luxury living room setup', category: 'Living Room' },
  { id: '2', image: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=600&q=80', alt: 'Modern bedroom design', category: 'Bedroom' },
  { id: '3', image: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=600&q=80', alt: 'Dining room with family', category: 'Dining' },
  { id: '4', image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80', alt: 'Hotel suite interior', category: 'Hotel' },
  { id: '5', image: 'https://images.unsplash.com/photo-1593642632559-0c6d3fc62b89?w=600&q=80', alt: 'Executive office setup', category: 'Office' },
  { id: '6', image: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=600&q=80', alt: 'Outdoor garden furniture', category: 'Outdoor' },
  { id: '7', image: 'https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=600&q=80', alt: 'Coffee table detail', category: 'Living Room' },
  { id: '8', image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80', alt: 'Wardrobe craftsmanship', category: 'Bedroom' },
  { id: '9', image: 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&q=80', alt: 'Showroom interior', category: 'Showroom' },
  { id: '10', image: 'https://images.unsplash.com/photo-1550581190-9c1c48d21d6c?w=600&q=80', alt: 'Workshop crafting', category: 'Workshop' },
  { id: '11', image: 'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=600&q=80', alt: 'Sofa detail texture', category: 'Living Room' },
  { id: '12', image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?w=600&q=80', alt: 'Bedroom corner styling', category: 'Bedroom' },
]

export const heroSlides = [
  {
    id: 1,
    heading: 'Modern Furniture',
    headingItalic: 'Ethiopian',
    subheading: 'Handcrafted with pride. Designed for modern living. Bringing warmth and elegance to every Ethiopian home.',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=1600&q=85',
    cta: 'Explore Products',
    ctaLink: '/products',
  },
  {
    id: 2,
    heading: 'Sleep in',
    headingItalic: 'Pure Luxury',
    subheading: 'Our bedroom collection blends Ethiopian craftsmanship with contemporary design for the ultimate rest experience.',
    image: 'https://images.unsplash.com/photo-1616594039964-ae9021a400a0?w=1600&q=85',
    cta: 'View Bedrooms',
    ctaLink: '/products?category=bedroom',
  },
  {
    id: 3,
    heading: 'Dine in',
    headingItalic: 'Style & Grace',
    subheading: 'Gather your family around furniture that tells a story — built to last generations, designed to inspire.',
    image: 'https://images.unsplash.com/photo-1615066390971-03e4e1c36ddf?w=1600&q=85',
    cta: 'View Dining',
    ctaLink: '/products?category=dining',
  },
]
